version: '3'

services:
  php:
    # image: php:8.1-apache
    build: ./dockerfiles/php
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
      - ./config/apache2:/etc/apache2
    ports:
      - "127.0.0.1:51210:80"
    networks:
      - nw_csgengine
  db:
    image: mariadb:10.7.1
    volumes:
      - ./maria_data:/var/lib/mysql
    ports:
      - "127.0.0.1:51211:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - nw_csgengine

volumes:
  maria_data:

networks:
  nw_csgengine:
    driver: bridge
